# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: SailingBonBini.com | To reach a port, you must set sail
email: sailingbonbini@gmail.com
author.name: Tom Doehler
description: > # this means to ignore newlines until "baseurl:"
       BonBini is a Dufour 36 classic, a perfect sailing boat to be handled
       by a couple as they hone their sailing skills and start living
       the cruising lifestyle. Follow our experience as we cut the cords and
       untie the lines, leaving behind the buzz of our busy city lives, and
       immerse ourselves in a life of sailing, anchoring, boating and generally
       living a happy cruisers life.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.sailingbonbini.com" # the base hostname & protocol for your site
twitter_username: sailingbonbini
github_username:  sailingbonbini

# Build settings
markdown: kramdown
theme: minima

defaults:
  site.slogan: To reach a port, you must set sail

